// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Greets the caller by name.
	 * 
	 *  # Arguments
	 *  * `name` - The name to greet.
	 * 
	 *  # Returns
	 *  A greeting message.
	 */
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	/**
	 *  Receives a structured log message from the frontend and rebroadcasts it.
	 * 
	 *  # Arguments
	 *  * `input` - The structured frontend log payload.
	 * 
	 *  # Returns
	 *  The enriched log entry that was dispatched.
	 */
	logMessage: (input: LogMessageInput) => __TAURI_INVOKE<LogEntry>("log_message", { input }),
};

/* Types */
export type LogContextItem = {
	key: string,
	value: string,
};

export type LogEntry = {
	timestampMs: number,
	level: LogLevel,
	source: LogSource,
	message: string,
	target: string | null,
	context: LogContextItem[],
	file: string | null,
	line: number | null,
	modulePath: string | null,
};

export type LogLevel = "trace" | "debug" | "info" | "warn" | "error";

export type LogMessageInput = {
	level: LogLevel,
	message: string,
	source?: LogSource,
	target?: string | null,
	context?: LogContextItem[],
	file?: string | null,
	line?: number | null,
	modulePath?: string | null,
};

export type LogSource = "frontend" | "backend";

